### ISSUE TITLE
crash after start

### ISSUE THREAD

**Issue by dslackw** [openclonk/openclonk#1]
Hello ,

I build openclonk on Slackware Linux and the game start normally but after start to play stop : 

$ openclonk
[00:23:41] Using XRandR version 1.4
[00:23:41] Command line: openclonk

(openclonk:30384): Gtk-WARNING **: Unable to locate theme engine in module_path: "mist",

(openclonk:30384): Gtk-WARNING **: Unable to locate theme engine in module_path: "mist",
/usr/share/themes/cyan/gtk-2.0/gtkrc:1703: error: unexpected string constant "GimpRuler*", expected character `='
[00:23:41] OpenClonk Beyond the Rocks
[00:23:41] Version: 5.4.1 linux-x86_64 (1066c4a4b3fe)
[00:23:41] Loading graphics...
[00:23:42] SDL_mixer runtime version is 1.2.12 (compiled with 1.2.12)
ALSA lib pcm.c:7843:(snd_pcm_recover) underrun occurred
[00:23:48] Scenario: /usr/share/games/openclonk//Tutorial.ocf/Tutorial01.ocs
[00:23:48] Scenario uses specified object definitions.
[00:23:48] Loading extras...
[00:23:48] Loading graphics...
[00:23:49] Loading object definitions:
[00:23:49] Objects.ocd...
5.4.1: Caught signal SIGFPE
openclonk[0x527705]
/lib64/libc.so.6(+0x36e50)[0x7fec8aca9e50]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x4aad15)[0x7fec82b9cd15]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x4ab57f)[0x7fec82b9d57f]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x31b605)[0x7fec82a0d605]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x2a5760)[0x7fec82997760]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x2addf1)[0x7fec8299fdf1]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x29a5e7)[0x7fec8298c5e7]
/usr/lib64/xorg/modules/dri/r600_dri.so(+0x29b854)[0x7fec8298d854]
openclonk(_ZN8C4TexRef6UnlockEv+0x178)[0x5eb348]
openclonk(_ZN8C4TexRefC2Eiib+0xd0)[0x5ecd50]
openclonk(_ZN9C4Surface14CreateTexturesEi+0x156)[0x5ed3a6]
openclonk(_ZN9C4Surface6CreateEiibbi+0x98)[0x5ed558]
openclonk(_ZN9C4Surface7ReadPNGER10CStdStream+0x93)[0x5edb93]
openclonk(_ZN9C4Surface4LoadER7C4GroupPKcbb+0x150)[0x5ee380]
openclonk(_ZN13C4DefGraphics10LoadBitmapER7C4GroupPKcS3_b+0x53)[0x74f933]
openclonk(_ZN13C4DefGraphics4LoadER7C4Groupb+0x71d)[0x75087d]
openclonk(_ZN5C4Def4LoadER7C4GroupjPKcP13C4SoundSystem+0x286)[0x74e926]
openclonk(_ZN9C4DefList4LoadER7C4GroupjPKcP13C4SoundSystembbiib+0x99)[0x7566a9]
openclonk(_ZN9C4DefList4LoadER7C4GroupjPKcP13C4SoundSystembbiib+0x273)[0x756883]
openclonk(_ZN9C4DefList4LoadER7C4GroupjPKcP13C4SoundSystembbiib+0x273)[0x756883]
openclonk(_ZN9C4DefList4LoadEPKcjS1_P13C4SoundSystembii+0x11e)[0x756bde]
openclonk(_ZN6C4Game8InitDefsEv+0x128)[0x591f88]
openclonk(_ZN6C4Game8InitGameER7C4GroupbbP14C4ValueNumbers+0x4aa)[0x5a125a]
openclonk(_ZN6C4Game4InitEv+0x532)[0x5a2eb2]
openclonk(_ZN13C4Application8GameTickEv+0x22e)[0x58ff1e]
openclonk(_ZN22C4ApplicationGameTimer7ExecuteEiP6pollfd+0xc2)[0x590102]
openclonk(_ZN12StdScheduler15DoScheduleProcsEi+0x3a1)[0x8296e1]
openclonk(_ZN12StdScheduler13ScheduleProcsEi+0x13d)[0x8288cd]
openclonk(_ZN13C4AbstractApp3RunEv+0x1d)[0x7b556d]
openclonk(main+0xe1)[0x51e1a1]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fec8ac94d85]
openclonk[0x52745d]

I think cannot load Objects.ocd and crash

Thanks

**Comment by walachey** [comment]
I will close the issue because there has been done so much with the graphics rendering since March 2014.
Please do reopen the issue if it persists with OpenClonk 7.0.
