### ISSUE TITLE
Assertion in C4AulFuncMap::~C4AulFuncMap fails.

### ISSUE THREAD

**Issue by fohly** [openclonk/openclonk#101]
The assertion in C4AulFuncMap::~C4AulFuncMap() fails when the editor is exited.

The assert line is
`assert(!FuncCnt);`

In my case FuncCnt is 3.

I have also found that e. g. "GetDefaultCancelSymbol" is added twice, but only removed once.

**Comment by lluchs** [comment]
I last fixed that assert triggering in <https://github.com/openclonk/openclonk/commit/950ad4cf2f992816c229bda43dcf805162e3faf4>, though I'm not sure whether I tested editor or fullscreen. Might be a good starting point for a bisect.

**Comment by isilkor** [comment]
I've merged your patch. Thanks for both the report and the fix!
