### ISSUE TITLE
Git build failure

### ISSUE THREAD

**Issue by psypherium** [openclonk/openclonk#119]
Building git from AUR fails here:

==> Starting prepare()...
patching file CMakeLists.txt
Hunk #1 FAILED at 167.
Hunk #2 FAILED at 1515.
Hunk #3 FAILED at 1538.

trying to build from this package: https://aur.archlinux.org/packages/openclonk-git

**Comment by lluchs** [comment]
cc @Fulgen301

**Comment by Fulgen301** [comment]
Uh. (https://aur.archlinux.org/cgit/aur.git/commit/?h=openclonk-git&id=f7b3bb7c13a126357275a9b64d9a3412b560890c)[That's messy.] Well, it should work for now.

**Comment by psypherium** [comment]
Works fine now, nice work :)
