### ISSUE TITLE
Making water disappear with an airplane

### ISSUE THREAD

**Issue by marsmoon** [openclonk/openclonk#56]
1. Fill a wooden barrel with water and poor that water into an airplane.
2. Continue doing that until the amount of water reaches its maximum value - 999.
3. Keep adding more water and notice that its amount inside of the plane stays the same, but the water disappears from your inventory.

![oc-plane](https://user-images.githubusercontent.com/30030740/31862904-88272c26-b735-11e7-95eb-e20bd45e1103.png)

**Comment by Armag3ddon** [comment]
Has been resolved.
