### ISSUE TITLE
Runtime join doesn't work on some maps

### ISSUE THREAD

**Issue by marsmoon** [openclonk/openclonk#58]
When runtime join is enabled, it will work on some maps, but on others joining clients will get desync, which will cause them to disconnect.

1. Here is a scenario that works with runtime join:
[RuntimeJoinTest.zip](https://github.com/openclonk/openclonk/files/1425623/RuntimeJoinTest.zip)
it has NPCs, buildings and an object that is moved constantly by a script

2. The same scenario with a few falling snowballs added to the map. It will not work.
[RuntimeJoinTest-broken-snow.zip](https://github.com/openclonk/openclonk/files/1425628/RuntimeJoinTest-broken-snow.zip)

3. Another version. This time with falling water. This one won't work either.
[RuntimeJoinTest-broken-water.zip](https://github.com/openclonk/openclonk/files/1425630/RuntimeJoinTest-broken-water.zip)

Looks like the desync that breaks runtime join is caused by moving liquids or snow, but it's possible that it's caused by physics in general. Those maps were not generated by a script.

**Comment by Fulgen301** [comment]
Runtime join is complicated - if only one bit goes wrong, there's a desync. But thank you for the attachments, they might be helpful to fix another issue of runtime join.

For future bug reports, please use the official OpenClonk bugtracker: http://bugs.openclonk.org

**Comment by isilkor** [comment]
We read bugs on here too, it's fine. (We would have turned off issues for the project if we didn't.)

**Comment by lluchs** [comment]
I looked into this and fixed a simple issue that made most scenarios desync immediately.

[Here's a script I used to test runtime join automatically using openclonk-server.](https://gist.github.com/lluchs/b1a1f28bf6eba6e0d0d39dced353cf5c) Your scenarios now seem to pass that script, but still desync when joining with the real engine:

```
FATAL ERROR: Network: Synchronization loss!
FATAL ERROR: Network: Client Frm 2656 Ctrl 885 Rnc 3 Cpx 17049 PXS 0 MMi 0 Obc 46 Oei 4921 Sct 91
FATAL ERROR: Network: Host   Frm 2656 Ctrl 885 Rnc 1 Cpx 17049 PXS 0 MMi 0 Obc 46 Oei 4924 Sct 91
```

Seems very similar to the issue I fixed (Oei is slightly higher on the host), so there might be more broken `OnSynchronized()` functions. I'm going to have another look next week.

**Comment by marsmoon** [comment]
In your log message only Rnc and Oei are different, for me also Sct is in scenario RuntimeJoinTest-broken-snow:
``
[00:00:07] Game joined.
[00:00:07] FATAL ERROR: Network: Synchronization loss!
[00:00:07] FATAL ERROR: Network: Client Frm 300 Ctrl 100 Rnc 306 Cpx 17000 PXS 0 MMi 0 Obc 48 Oei 206 Sct 87
[00:00:07] FATAL ERROR: Network: Host Frm 300 Ctrl 100 Rnc 315 Cpx 17000 PXS 0 MMi 0 Obc 48 Oei 201 Sct 90
``

In RuntimeJoinTest-broken-water I get this:
``
[23:58:19] Game joined.
[23:58:19] FATAL ERROR: Network: Synchronization loss!
[23:58:19] FATAL ERROR: Network: Client Frm 500 Ctrl 166 Rnc 185 Cpx 17000 PXS 0 MMi 0 Obc 45 Oei 366 Sct 89
[23:58:19] FATAL ERROR: Network: Host Frm 500 Ctrl 166 Rnc 537 Cpx 17000 PXS 0 MMi 65 Obc 45 Oei 365 Sct 88
``

The issue for those maps has to be something related to particles or physics, since water and snow are the only changes among their versions.

**Comment by lluchs** [comment]
I found the issue with landscape saving and I think runtime join works fine now!

**Comment by marsmoon** [comment]
It's working, great job!
