### ISSUE TITLE
[Openclonk-8.1] blake2 needs SSE2 support

### ISSUE THREAD

**Issue by sagitter** [openclonk/openclonk#69]
Hello everyone.

`SSE2` support needed by `blake2` shipped inside `openclonk-8.1` is unavailable in most no-64bit CPUs; this is a serious limitation for compiling `openclonk`.

Is there a way to fix this situation?

**Comment by Armag3ddon** [comment]
As of now, probably not. We'll have to use something else, then.
Just out of curiousity, what kind of CPU are you using?

**Comment by sagitter** [comment]
>As of now, probably not. We'll have to use something else, then.

Could be faster for you using a pre-compiled `blake2` and not that inside `openclonk` source code?

**Comment by isilkor** [comment]
We can probably ship the C reference implementation of BLAKE2b as well 
and fall back to that for architectures other than x64.

**Comment by sagitter** [comment]
@isilkor 

Exactly, this can resolve the problem.

**Comment by sagitter** [comment]
Thank you all.
