### ISSUE TITLE
Support for ligua PT-BR

### ISSUE THREAD

**Issue by LeandroStanger** [openclonk/openclonk#70]

**Comment by Armag3ddon** [comment]
I don't if Clonk supports these sub-language demonimations. But for a start, one could call it PT or BR.
OC does support third party language packs, however. In case you're interested in a translation, let us know. We can walk you through the steps. Mind you, of course, that this is a lot of work!

**Comment by jcaesar** [comment]
@LeandroStanger Please feel free to reopen provide more details on what you think is missing for the language support.

Also note that translating OpenClonk requires translating around 550 files with a total size of around 250kB. While not an endless endeavor, it's not something that happens in an evening. Unless you are willing to spend time on it, it's probably not happening.
