### ISSUE TITLE
Crash caused by C4Script

### ISSUE THREAD

**Issue by bratkartoff** [openclonk/openclonk#79]
The following code causes a crash on Openclonk 9.0 (Windows), Openclonk 8.1 Linux (and on Clonk Rage as well)

private func Initialize() {
	Test([[]]);
}

private func Test(a) {
	if (GetType(a) == C4V_Int)
		return 0;
	SetLength(a, 1);
	Test(a[0]);
	return 0;
}

Edit: Test map
[Crashtest.ocs.zip](https://github.com/openclonk/openclonk/files/2729728/Crashtest.ocs.zip)

**Comment by isilkor** [comment]
Testcase can be reduced to
`func f() { SetLength(nil, 0); }`. SetLength always crashes when the first parameter is nil.

**Comment by isilkor** [comment]
Fixed in #80.
